import type { WorkOrderListItem } from '../api/workOrdersRepository';

export const DEMO_TENANT_ID = 'demo-hospital';
export const DEMO_TECHNICIAN_ID = 'demo-tech-1';
export const DEMO_SECOND_TECHNICIAN_ID = 'demo-tech-2';

const commonRequirements = {
  checklist: true,
  initialPhotos: true,
  finalPhotos: true,
  measurements: false,
  materials: false,
  technicianSignature: true,
  responsibleSignature: false,
  finalFunctionalTest: true,
  report: true,
  administrativeReview: true,
} as const;

export const demoWorkOrders: WorkOrderListItem[] = [
  {
    id: 'demo-ot-001',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000241',
    title: 'Reparar amplificador de señal TV',
    description: 'La televisión del estar de enfermería presenta cortes y baja calidad de señal. Revisar alimentación, ganancia, derivadores, tomas y cableado coaxial.',
    type: 'averia',
    priority: 'alta',
    status: 'EN_CURSO',
    siteId: 'demo-site-pts',
    locationId: 'demo-location-2a',
    assetId: 'demo-asset-tv-amp',
    assignedTo: DEMO_TECHNICIAN_ID,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-17T08:30:00.000Z',
    dueAt: '2026-07-17T13:00:00.000Z',
    estimatedMinutes: 90,
    instructions: 'Medir señal a la entrada y salida del amplificador antes de sustituir componentes.',
    safetyNotes: 'Desconectar alimentación antes de manipular el amplificador y verificar ausencia de tensión.',
    expectedResult: 'Nivel y calidad de señal estables en todas las tomas del estar de enfermería.',
    requirements: { ...commonRequirements, measurements: true },
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-17T06:42:00.000Z',
    updatedAt: '2026-07-17T09:24:00.000Z',
    siteName: 'Hospital Universitario PTS',
    locationName: 'Planta 2 · Estar de enfermería',
    assignedToName: 'Carlos Martínez',
  },
  {
    id: 'demo-ot-002',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000242',
    title: 'Nueva línea eléctrica para lavacuñas',
    description: 'Instalar una nueva línea independiente para el lavacuñas, con protección magnetotérmica de 20 A y diferencial de 30 mA.',
    type: 'instalacion',
    priority: 'urgente',
    status: 'ASIGNADA',
    siteId: 'demo-site-pts',
    locationId: 'demo-location-3b',
    assetId: 'demo-asset-lavacunas',
    assignedTo: DEMO_TECHNICIAN_ID,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-18T06:30:00.000Z',
    dueAt: '2026-07-18T11:00:00.000Z',
    estimatedMinutes: 180,
    instructions: 'Comprobar sección, recorrido, identificación y selectividad de las protecciones.',
    safetyNotes: 'Aplicar consignación y señalización. Verificar ausencia de tensión antes de intervenir.',
    expectedResult: 'Lavacuñas alimentado mediante circuito exclusivo, probado y correctamente identificado.',
    requirements: { ...commonRequirements, measurements: true, responsibleSignature: true },
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-17T07:10:00.000Z',
    updatedAt: '2026-07-17T07:55:00.000Z',
    siteName: 'Hospital Universitario PTS',
    locationName: 'Planta 3 · Cuarto de limpieza',
    assignedToName: 'Carlos Martínez',
  },
  {
    id: 'demo-ot-003',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000243',
    title: 'Revisión batería de condensadores CT-2',
    description: 'Revisar alarma A.02, estado de fusibles, contactores, condensadores y regulación del factor de potencia.',
    type: 'revision',
    priority: 'alta',
    status: 'BLOQUEADA',
    siteId: 'demo-site-pts',
    locationId: 'demo-location-n1',
    assetId: 'demo-asset-bateria-ct2',
    assignedTo: DEMO_SECOND_TECHNICIAN_ID,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-17T10:00:00.000Z',
    dueAt: '2026-07-18T12:00:00.000Z',
    estimatedMinutes: 120,
    instructions: 'Registrar intensidades por escalón y comprobar temperatura y ruido anormal.',
    safetyNotes: 'Trabajo en cuadro eléctrico. Utilizar EPI y procedimiento de consignación.',
    expectedResult: 'Batería sin alarmas, escalones equilibrados y cos φ dentro del rango previsto.',
    requirements: { ...commonRequirements, measurements: true, materials: true },
    blockReason: 'MATERIAL',
    blockNotes: 'Pendiente de recibir dos fusibles NH de 100 A.',
    createdAt: '2026-07-16T11:14:00.000Z',
    updatedAt: '2026-07-17T10:38:00.000Z',
    siteName: 'Hospital Universitario PTS',
    locationName: 'Nivel -1 · Centro de transformación 2',
    assignedToName: 'Miguel López',
  },
  {
    id: 'demo-ot-004',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000244',
    title: 'Cambio de cámara y baliza de habitación',
    description: 'Sustituir la cámara de seguridad arrancada y la baliza de señalización de la habitación 311.',
    type: 'sustitucion',
    priority: 'normal',
    status: 'FINALIZADA_TECNICO',
    siteId: 'demo-site-pts',
    locationId: 'demo-location-311',
    assetId: null,
    assignedTo: DEMO_TECHNICIAN_ID,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-16T07:00:00.000Z',
    dueAt: '2026-07-16T12:00:00.000Z',
    estimatedMinutes: 75,
    instructions: 'Verificar fijación, orientación, alimentación y funcionamiento de ambos elementos.',
    safetyNotes: 'Delimitar la zona de trabajo y utilizar escalera homologada.',
    expectedResult: 'Cámara y baliza instaladas, firmes y operativas.',
    requirements: commonRequirements,
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-15T13:20:00.000Z',
    updatedAt: '2026-07-16T09:52:00.000Z',
    siteName: 'Hospital Universitario PTS',
    locationName: 'Planta 3 · Habitación 311',
    assignedToName: 'Carlos Martínez',
  },
  {
    id: 'demo-ot-005',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000245',
    title: 'Ajuste de variador de extracción de cocina',
    description: 'El variador presenta alarma F004. Revisar consignas, parámetros de marcha y señal del programador.',
    type: 'mantenimiento_correctivo',
    priority: 'critica',
    status: 'VALIDADA',
    siteId: 'demo-site-pts',
    locationId: 'demo-location-kitchen',
    assetId: 'demo-asset-vfd-kitchen',
    assignedTo: DEMO_SECOND_TECHNICIAN_ID,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-15T06:30:00.000Z',
    dueAt: '2026-07-15T09:30:00.000Z',
    estimatedMinutes: 90,
    instructions: 'Comprobar F012, D012 y P106; registrar estado antes y después del reset.',
    safetyNotes: 'No alimentar el motor directamente fuera del variador durante la prueba.',
    expectedResult: 'Extracción funcionando sin alarmas y con regulación estable.',
    requirements: { ...commonRequirements, measurements: true },
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-15T05:50:00.000Z',
    updatedAt: '2026-07-15T09:18:00.000Z',
    siteName: 'Hospital Universitario PTS',
    locationName: 'Nivel -1 · Cocina',
    assignedToName: 'Miguel López',
  },
  {
    id: 'demo-ot-006',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000246',
    title: 'Comprobar relé de falta de fase RM4TR32',
    description: 'El contactor conecta y desconecta repetidamente. Verificar tensiones, secuencia de fases y ajuste del relé.',
    type: 'medicion',
    priority: 'alta',
    status: 'ACEPTADA',
    siteId: 'demo-site-pts',
    locationId: 'demo-location-machine-room',
    assetId: 'demo-asset-rm4tr32',
    assignedTo: DEMO_TECHNICIAN_ID,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-19T07:00:00.000Z',
    dueAt: '2026-07-19T10:00:00.000Z',
    estimatedMinutes: 60,
    instructions: 'Medir tensión entre fases y comprobar que el ajuste corresponde a la tensión nominal de red.',
    safetyNotes: 'Medición en tensión: usar instrumentación CAT adecuada y EPI eléctrico.',
    expectedResult: 'Relé estable, ajuste correcto y contactor sin ciclos repetitivos.',
    requirements: { ...commonRequirements, measurements: true, initialPhotos: false },
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-17T12:20:00.000Z',
    updatedAt: '2026-07-17T12:48:00.000Z',
    siteName: 'Hospital Universitario PTS',
    locationName: 'Planta 9 · Sala técnica',
    assignedToName: 'Carlos Martínez',
  },
  {
    id: 'demo-ot-007',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000247',
    title: 'Inspección semanal de purgas ACS',
    description: 'Realizar purga de tres minutos en puntos terminales incluidos en el programa de control de legionela.',
    type: 'inspeccion',
    priority: 'normal',
    status: 'BORRADOR',
    siteId: 'demo-site-pts',
    locationId: 'demo-location-mental-health',
    assetId: null,
    assignedTo: null,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-20T06:00:00.000Z',
    dueAt: '2026-07-20T13:00:00.000Z',
    estimatedMinutes: 150,
    instructions: 'Registrar temperatura, tiempo de purga y observaciones de cada punto.',
    safetyNotes: 'Prevenir salpicaduras y riesgo de quemadura por agua caliente.',
    expectedResult: 'Todos los puntos asignados purgados y registrados.',
    requirements: { ...commonRequirements, measurements: true, initialPhotos: false, finalPhotos: false },
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-17T13:05:00.000Z',
    updatedAt: '2026-07-17T13:05:00.000Z',
    siteName: 'Hospital Universitario PTS',
    locationName: 'Planta 2 · Salud mental',
    assignedToName: null,
  },
  {
    id: 'demo-ot-008',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000248',
    title: 'Sustituir pantalla de iluminación de almacén',
    description: 'Recolocar luminarias de pasillo y añadir una pantalla donde actualmente no existe iluminación suficiente.',
    type: 'instalacion',
    priority: 'baja',
    status: 'CANCELADA',
    siteId: 'demo-site-pts',
    locationId: 'demo-location-warehouse',
    assetId: null,
    assignedTo: null,
    createdBy: 'demo-admin',
    plannedAt: null,
    dueAt: null,
    estimatedMinutes: 120,
    instructions: null,
    safetyNotes: 'Trabajos en altura con escalera homologada y zona balizada.',
    expectedResult: 'Nivel de iluminación uniforme en pasillos y puestos de trabajo.',
    requirements: commonRequirements,
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-14T08:12:00.000Z',
    updatedAt: '2026-07-14T10:40:00.000Z',
    siteName: 'Hospital Universitario PTS',
    locationName: 'Nivel -1 · Almacén general',
    assignedToName: null,
  },
];

export function nextDemoOrderCode(orders: WorkOrderListItem[]): string {
  const highest = orders.reduce((current, order) => {
    const match = order.code.match(/(\d+)$/);
    return Math.max(current, match ? Number(match[1]) : 0);
  }, 0);
  return `OT-2026-${String(highest + 1).padStart(6, '0')}`;
}
