import type { WorkOrderListItem } from '../api/workOrdersRepository';

export const DEMO_TENANT_ID = 'demo-fv-maintenance';
export const DEMO_TECHNICIAN_ID = 'demo-tech-1';
export const DEMO_SECOND_TECHNICIAN_ID = 'demo-tech-2';

const commonRequirements = {
  checklist: true,
  initialPhotos: true,
  finalPhotos: true,
  measurements: false,
  materials: false,
  technicianSignature: true,
  responsibleSignature: false,
  finalFunctionalTest: true,
  report: true,
  administrativeReview: true,
} as const;

export const demoWorkOrders: WorkOrderListItem[] = [
  {
    id: 'demo-ot-001',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000241',
    title: 'Revisar inversor FV de autoconsumo',
    description: 'El inversor principal registra avisos intermitentes y bajada de producción. Revisar alarmas, ventilación, conexiones DC/AC, tensiones de string y comunicación con monitorización.',
    type: 'averia',
    priority: 'alta',
    status: 'EN_CURSO',
    siteId: 'demo-site-fv-jaen',
    locationId: 'demo-location-inverter-room',
    assetId: 'demo-asset-inverter-100kw',
    assignedTo: DEMO_TECHNICIAN_ID,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-17T08:30:00.000Z',
    dueAt: '2026-07-17T13:00:00.000Z',
    estimatedMinutes: 90,
    instructions: 'Descargar eventos del inversor, medir DC/AC y dejar capturas de la monitorización antes y después de la intervención.',
    safetyNotes: 'Aplicar procedimiento eléctrico FV: seccionamiento DC/AC, verificación de ausencia de tensión donde proceda y EPIs eléctricos.',
    expectedResult: 'Inversor sin alarmas activas, producción estable y comunicación operativa en plataforma.',
    requirements: { ...commonRequirements, measurements: true },
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-17T06:42:00.000Z',
    updatedAt: '2026-07-17T09:24:00.000Z',
    siteName: 'SolarManten FV · Planta Jaén',
    locationName: 'Sala técnica · Inversores',
    assignedToName: 'Carlos Martínez',
    assetName: 'Inversor Huawei SUN2000 100 kW',
    assetType: 'Inversor fotovoltaico',
    assetReference: 'FV-INV-001',
    assetCriticality: 'alta',
    assetStatus: 'operativo_con_avisos',
  },
  {
    id: 'demo-ot-002',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000242',
    title: 'Termografía y revisión de strings',
    description: 'Realizar inspección termográfica de strings del campo 3 y comprobar conectores, cajas de string y posibles puntos calientes.',
    type: 'inspeccion',
    priority: 'urgente',
    status: 'ASIGNADA',
    siteId: 'demo-site-fv-jaen',
    locationId: 'demo-location-field-3',
    assetId: 'demo-asset-stringbox-03',
    assignedTo: DEMO_TECHNICIAN_ID,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-18T06:30:00.000Z',
    dueAt: '2026-07-18T11:00:00.000Z',
    estimatedMinutes: 180,
    instructions: 'Tomar imágenes térmicas con irradiancia suficiente y registrar strings con desviación de temperatura.',
    safetyNotes: 'Trabajo en exterior y zona FV energizada. Señalizar zona, usar EPIs y no manipular conectores bajo carga.',
    expectedResult: 'Strings revisados, puntos calientes documentados y acciones correctivas propuestas.',
    requirements: { ...commonRequirements, measurements: true, responsibleSignature: true },
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-17T07:10:00.000Z',
    updatedAt: '2026-07-17T07:55:00.000Z',
    siteName: 'SolarManten FV · Planta Jaén',
    locationName: 'Campo FV 3 · Strings 3.1-3.8',
    assignedToName: 'Carlos Martínez',
    assetName: 'Caja de strings Campo 3',
    assetType: 'Cuadro DC',
    assetReference: 'FV-CST-003',
    assetCriticality: 'alta',
    assetStatus: 'pendiente_revision',
  },
  {
    id: 'demo-ot-003',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000243',
    title: 'Sustituir fusibles NH en cuadro AC',
    description: 'Revisar protección de salida AC, sustituir fusibles deteriorados y comprobar apriete, temperatura y equilibrio de fases.',
    type: 'mantenimiento_correctivo',
    priority: 'alta',
    status: 'BLOQUEADA',
    siteId: 'demo-site-fv-jaen',
    locationId: 'demo-location-ac-board',
    assetId: 'demo-asset-ac-board-main',
    assignedTo: DEMO_SECOND_TECHNICIAN_ID,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-17T10:00:00.000Z',
    dueAt: '2026-07-18T12:00:00.000Z',
    estimatedMinutes: 120,
    instructions: 'Registrar intensidades por fase, temperatura de embarrado y estado de portafusibles antes de cerrar.',
    safetyNotes: 'Trabajo en cuadro AC. Consignación, verificación y EPIs obligatorios.',
    expectedResult: 'Cuadro AC sin sobretemperaturas, protecciones sustituidas y mediciones dentro de rango.',
    requirements: { ...commonRequirements, measurements: true, materials: true },
    blockReason: 'MATERIAL',
    blockNotes: 'Pendiente de recibir dos fusibles NH de 160 A.',
    createdAt: '2026-07-16T11:14:00.000Z',
    updatedAt: '2026-07-17T10:38:00.000Z',
    siteName: 'SolarManten FV · Planta Jaén',
    locationName: 'Sala técnica · Cuadro general AC',
    assignedToName: 'Miguel López',
    assetName: 'Cuadro general AC FV',
    assetType: 'Cuadro eléctrico AC',
    assetReference: 'FV-AC-001',
    assetCriticality: 'critica',
    assetStatus: 'bloqueado_por_material',
  },
  {
    id: 'demo-ot-004',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000244',
    title: 'Revisión de estructura y pares de apriete',
    description: 'Revisar fijaciones de estructura en cubierta, reapriete de grapas, comprobación visual de corrosión y sujeción de cableado.',
    type: 'revision',
    priority: 'normal',
    status: 'FINALIZADA_TECNICO',
    siteId: 'demo-site-client-rooftop',
    locationId: 'demo-location-rooftop-north',
    assetId: 'demo-asset-rooftop-structure',
    assignedTo: DEMO_TECHNICIAN_ID,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-16T07:00:00.000Z',
    dueAt: '2026-07-16T12:00:00.000Z',
    estimatedMinutes: 75,
    instructions: 'Fotografiar zonas revisadas y anotar cualquier fijación sustituida.',
    safetyNotes: 'Trabajo en cubierta. Usar línea de vida, arnés y control de acceso a zona de trabajo.',
    expectedResult: 'Estructura revisada, sin elementos flojos y con evidencias fotográficas finales.',
    requirements: commonRequirements,
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-15T13:20:00.000Z',
    updatedAt: '2026-07-16T09:52:00.000Z',
    siteName: 'Cliente Industrial · Nave Norte',
    locationName: 'Cubierta nave norte · Zona A',
    assignedToName: 'Carlos Martínez',
    assetName: 'Estructura coplanar cubierta norte',
    assetType: 'Estructura FV',
    assetReference: 'FV-EST-010',
    assetCriticality: 'normal',
    assetStatus: 'revisado',
  },
  {
    id: 'demo-ot-005',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000245',
    title: 'Restablecer monitorización de planta',
    description: 'El portal de monitorización no actualiza datos. Revisar router, datalogger, alimentación, tarjeta SIM y comunicación con inversores.',
    type: 'mantenimiento_correctivo',
    priority: 'critica',
    status: 'VALIDADA',
    siteId: 'demo-site-fv-jaen',
    locationId: 'demo-location-comms',
    assetId: 'demo-asset-datalogger',
    assignedTo: DEMO_SECOND_TECHNICIAN_ID,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-15T06:30:00.000Z',
    dueAt: '2026-07-15T09:30:00.000Z',
    estimatedMinutes: 90,
    instructions: 'Comprobar alimentación, conectividad y lectura de datos en plataforma antes de cerrar.',
    safetyNotes: 'No reiniciar equipos de comunicación sin documentar estado previo y hora de intervención.',
    expectedResult: 'Monitorización recuperada y datos visibles en plataforma del cliente.',
    requirements: { ...commonRequirements, measurements: true },
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-15T05:50:00.000Z',
    updatedAt: '2026-07-15T09:18:00.000Z',
    siteName: 'SolarManten FV · Planta Jaén',
    locationName: 'Sala técnica · Comunicaciones',
    assignedToName: 'Miguel López',
    assetName: 'Datalogger y router 4G',
    assetType: 'Monitorización',
    assetReference: 'FV-COM-001',
    assetCriticality: 'critica',
    assetStatus: 'operativo',
  },
  {
    id: 'demo-ot-006',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000246',
    title: 'Comprobar relé de falta de fase',
    description: 'El contactor del cuadro de bombeo solar conecta y desconecta repetidamente. Verificar tensiones, secuencia de fases y ajuste del relé.',
    type: 'medicion',
    priority: 'alta',
    status: 'ACEPTADA',
    siteId: 'demo-site-fv-jaen',
    locationId: 'demo-location-pump-room',
    assetId: 'demo-asset-phase-relay',
    assignedTo: DEMO_TECHNICIAN_ID,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-19T07:00:00.000Z',
    dueAt: '2026-07-19T10:00:00.000Z',
    estimatedMinutes: 60,
    instructions: 'Medir tensión entre fases y comprobar que el ajuste corresponde a la tensión nominal de red.',
    safetyNotes: 'Medición en tensión: usar instrumentación CAT adecuada y EPI eléctrico.',
    expectedResult: 'Relé estable, ajuste correcto y contactor sin ciclos repetitivos.',
    requirements: { ...commonRequirements, measurements: true, initialPhotos: false },
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-17T12:20:00.000Z',
    updatedAt: '2026-07-17T12:48:00.000Z',
    siteName: 'SolarManten FV · Planta Jaén',
    locationName: 'Cuarto técnico · Bombeo solar',
    assignedToName: 'Carlos Martínez',
    assetName: 'Relé control de fases bombeo',
    assetType: 'Protección eléctrica',
    assetReference: 'FV-REL-004',
    assetCriticality: 'alta',
    assetStatus: 'en_revision',
  },
  {
    id: 'demo-ot-007',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000247',
    title: 'Preventivo trimestral de planta FV',
    description: 'Realizar checklist preventivo de campo FV, limpieza visual, revisión de cuadros, estado de cableado, señalización y producción.',
    type: 'mantenimiento_preventivo',
    priority: 'normal',
    status: 'BORRADOR',
    siteId: 'demo-site-fv-jaen',
    locationId: 'demo-location-general',
    assetId: null,
    assignedTo: null,
    createdBy: 'demo-admin',
    plannedAt: '2026-07-20T06:00:00.000Z',
    dueAt: '2026-07-20T13:00:00.000Z',
    estimatedMinutes: 150,
    instructions: 'Registrar mediciones principales, incidencias detectadas y fotografías de cuadros y campo.',
    safetyNotes: 'Trabajos en exterior: revisar meteorología, hidratación y control de acceso.',
    expectedResult: 'Preventivo registrado con checklist, mediciones y recomendaciones.',
    requirements: { ...commonRequirements, measurements: true, initialPhotos: false, finalPhotos: false },
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-17T13:05:00.000Z',
    updatedAt: '2026-07-17T13:05:00.000Z',
    siteName: 'SolarManten FV · Planta Jaén',
    locationName: 'Planta FV completa',
    assignedToName: null,
    assetName: null,
    assetType: null,
    assetReference: null,
    assetCriticality: null,
    assetStatus: null,
  },
  {
    id: 'demo-ot-008',
    tenantId: DEMO_TENANT_ID,
    code: 'OT-2026-000248',
    title: 'Sustituir luminaria LED en almacén técnico',
    description: 'Sustituir luminaria del almacén de repuestos y revisar interruptor, conexión y nivel de iluminación en zona de trabajo.',
    type: 'instalacion',
    priority: 'baja',
    status: 'CANCELADA',
    siteId: 'demo-site-base',
    locationId: 'demo-location-warehouse',
    assetId: null,
    assignedTo: null,
    createdBy: 'demo-admin',
    plannedAt: null,
    dueAt: null,
    estimatedMinutes: 120,
    instructions: null,
    safetyNotes: 'Trabajos en altura con escalera homologada y zona balizada.',
    expectedResult: 'Nivel de iluminación suficiente para preparar material y repuestos.',
    requirements: commonRequirements,
    blockReason: null,
    blockNotes: null,
    createdAt: '2026-07-14T08:12:00.000Z',
    updatedAt: '2026-07-14T10:40:00.000Z',
    siteName: 'Base de mantenimiento · Almacén',
    locationName: 'Almacén técnico · Repuestos FV',
    assignedToName: null,
    assetName: null,
    assetType: null,
    assetReference: null,
    assetCriticality: null,
    assetStatus: null,
  },
];

export function nextDemoOrderCode(orders: WorkOrderListItem[]): string {
  const highest = orders.reduce((current, order) => {
    const match = order.code.match(/(\d+)$/);
    return Math.max(current, match ? Number(match[1]) : 0);
  }, 240);
  return `OT-2026-${String(highest + 1).padStart(6, '0')}`;
}
